# storageCapacity is the minimum capacity for MySQL data storage
storageCapacity: 1Gi
# storageClassName is the StorageClass used for the MySQL PVC
storageClassName:

# password is the MySQL root user password
password: something