apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-adminer-dep
  labels:
    program: helm
    sample: dbapp
{{ include "mysql.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      program: helm
      sample: dbapp
      layer: frontend
{{ include "mysql.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        program: helm
        sample: dbapp
        layer: frontend
{{ include "mysql.labels" . | indent 8 }}
    spec:
      containers:
        - name: webserver
          image: adminer:4.7
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: {{ .Release.Name }}-mysql-svc
