{{- if index .Values.tags "include-np" -}}
{{- if has "networking.k8s.io/v1/NetworkPolicy" .Capabilities.APIVersions -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-dbapp-np
  labels:
    program: helm
    sample: dbapp
{{ include "common.labels" . | indent 4}}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      program: helm
      sample: mysql
      layer: database
{{ include "common.labels" . | indent 6 }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              program: helm
              sample: dbapp
              layer: frontend
{{ include "common.labels" . | indent 14 }}
      ports:
        - port: 3306
{{- end -}}
{{- end -}}