apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-dep
  labels:
    program: helm
    sample: mysql
{{ include "mysql.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      program: helm
      sample: mysql
      layer: database
{{ include "mysql.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        program: helm
        sample: mysql
        layer: database
{{ include "mysql.labels" . | indent 8 }}
    spec:
      volumes:
        - name: dbvol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
      containers:
        - name: c1
          image: mysql:5.7
          volumeMounts:
            - name: dbvol
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
{{- if .Values.secretKey }}
              valueFrom:
                secretKeyRef:
{{- if .Values.secretName }}
                  name: {{ .Values.secretName }}
{{- else }}
                  name: {{ .Release.Name }}-mysql-sec
{{- end }}
                  key: {{ .Values.secretKey }}
{{- else }}
              value: {{ .Values.password }}
{{- end }}