apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-svc
  labels:
    program: helm
    sample: mysql
{{ include "mysql.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    program: helm
    sample: mysql
    layer: database
{{ include "mysql.labels" . | indent 4 }}
  ports:
    - name: mysql
      port: 3306