apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  labels:
    program: helm
    sample: mysql
{{ include "mysql.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "1Gi" .Values.storageCapacity }}
{{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
{{- end }}
