apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  labels:
    program: helm
    sample: mysql
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.Capacity }}
