apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  labels:
    program: helm
    sample: mysql
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "1Gi" .Values.storage.Capacity }}
  {{ if .Values.storage.StorageClassName }}storageClassName: {{ .Values.storage.StorageClassName }}{{ end }}
